# Generated by Django 4.2.1 on 2023-09-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filme",
            old_name="titulo",
            new_name="nome",
        ),
    ]
